version: "3.8"
services:
  mocked-server:
    build:
      context: ../../mocked_server
    ports:
      - 80:8080

  aws-ot-collector:
    build:
      context: ../../../aws-otel-collector
      dockerfile: cmd/awscollector/Dockerfile

    command: ["--config=/tmp/otconfig.yaml", "--log-level=DEBUG"]
    volumes:
      - ./otconfig.yml:/tmp/otconfig.yaml
      - "../../mocked_server/certificates/ssl/certificate.crt:/etc/ssl/certs/ca-certificates.crt"
      - "../../mocked_server/certificates/ssl/certificate.crt:/etc/ssl/cert.pem"
      - "../../mocked_server/certificates/ssl/certificate.crt:/etc/pki/tls/certs/ca-bundle.crt"
      - "../../mocked_server/certificates/ssl/certificate.crt:/etc/ssl/ca-bundle.pem"
      - "../../mocked_server/certificates/ssl/certificate.crt:/etc/pki/tls/cacert.pem"
      - "../../mocked_server/certificates/ssl/certificate.crt:/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
    environment:
      - AWS_ACCESS_KEY_ID=AKIAY6WBBCFAKEOX7IQR
      - AWS_SECRET_ACCESS_KEY=QY5DfUyosEa0efakejlteLvHxabKaeQ5zuppF9v7
      - AWS_REGION=us-west-2
      - GODEBUG=x509ignoreCN=0
    depends_on:
      - mocked-server

  sample_app:
    image: josephwy/integ-test-emitter:alpine
    ports:
      - "4567:4567"
    environment:
      - LISTEN_ADDRESS=0.0.0.0:4567
      - AWS_REGION=us-west-2
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=YingOtel,service.name=Terraform
      - INSTANCE_ID=925ae701b012b0bc
      - OTEL_EXPORTER_OTLP_ENDPOINT=aws-ot-collector:55680
      - AWS_XRAY_DAEMON_ADDRESS=aws-ot-collector:55690
    depends_on:
      - aws-ot-collector