version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    groups:
      github-actions-deps:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    # Files stored in `cmd/aoutil` directory
    directory: "/cmd/aoutil"
    schedule:
      interval: "weekly"
      day: "tuesday"
    groups:
      aotutil-deps:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    # Files stored in `/mocked_servers/grpc_metrics` directory
    directory: "/mocked_servers/grpc_metrics"
    schedule:
      interval: "weekly"
      day: "tuesday"
    groups:
      mocked-server-grpc-metric-deps:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    # Files stored in `/mocked_servers/grpc_trace` directory
    directory: "/mocked_servers/grpc_trace"
    schedule:
      interval: "weekly"
      day: "tuesday"
    groups:
      mocked-server-grpc-race-deps:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    # Files stored in `/mocked_servers/https` directory
    directory: "/mocked_servers/https"
    schedule:
      interval: "weekly"
      day: "tuesday"
    groups:
      mocked-server-https-deps:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    # build.gradle stored in repository root
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    groups:
      root-gradle-deps:
        patterns:
          - "*"
    ignore:
      - dependency-name: "com.github.fge:json-schema-validator"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"


  - package-ecosystem: "gradle"
    # build.gradle stored in `/load-generator` directory
    directory: "/load-generator"
    schedule:
      interval: "weekly"
      day: "tuesday"
    groups:
      load-gen-gradle-deps:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    # build.gradle file stored in `/trace-java-client` directory
    directory: "/trace-java-client"
    schedule:
      interval: "weekly"
      day: "tuesday"
    groups:
      trace-java-client-gradle-deps:
        patterns:
          - "*"
  
  - package-ecosystem: "npm"
    directory: "/cdk_infra"
    schedule:
      interval: "weekly"
      day: "tuesday"
    groups:
      cdk-infra-deps:
        patterns:
          - "*"
