aoc_iam_role_name="aoc-e2e-iam-role"
region="us-west-2"
package_s3_bucket="aws-observability-collector-test"
sshkey_s3_bucket="aoc-ssh-key"
sshkey_s3_public_key="aoc-ssh.pem"
sshkey_s3_private_key="aoc-ssh-private"
ssh_key_name="aoc-ssh-key-for-ec2"
security_group_name="aoc-test-security-group"
validator_path="/app/validator/bin/validator"

testing_ami="amazonlinux2"
