/*
 * Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.amazon.aocagent;

import com.amazon.aocagent.commands.Candidate;
import com.amazon.aocagent.commands.IntegTest;
import com.amazon.aocagent.commands.Release;
import com.amazon.aocagent.commands.ResourceClean;
import com.amazon.aocagent.commands.Setup;
import lombok.extern.log4j.Log4j2;
import picocli.CommandLine;

@CommandLine.Command(
    name = "aoccicd",
    mixinStandardHelpOptions = true,
    version = "0.1",
    description = "use for integtests and releases of the aocagent",
    subcommands = {
      IntegTest.class,
      Release.class,
      Candidate.class,
      Setup.class,
      ResourceClean.class
    })
@Log4j2
public class App implements Runnable {
  public static void main(String[] args) {
    int exitCode = new CommandLine(new App()).execute(args);
    System.exit(exitCode);
  }

  @Override
  public void run() {
    log.info("Starting");
  }
}
