name: Main build

on:
  push:
    branches: [ terraform ]

permissions:
  id-token: write
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
    - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 #v5.0.0
      with:
        distribution: 'zulu'
        java-version: 17
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 #v5.0.0
      with:
        role-to-assume: ${{ secrets.INTEG_TEST_TFW_ROLE_ARN }}
        role-duration-seconds: 1200
        aws-region: us-east-1
    - name: Login to ECR
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 #v3.5.0
      with:
        registry: public.ecr.aws
    - name: Push validator docker image
      uses: burrunan/gradle-cache-action@c15634bb25b7284dc084f38dff4e838048b7feaf #v2
      with:
        arguments: :validator:jib --stacktrace
